### PR TITLE
Fixes: adress renaming (#191), also check in usable policy that block is >= 0

### LINKED ISSUE #191: wording: let's use "unikernel" instead of "vm"
in various pretty-printers and help functions we use the term vm at the moment, while unikernel is more appropriate

### PR DESCRIPTION
**Pull request by hannesm**
- fixes #191
- addresses https://github.com/robur-coop/mollymawk/pull/57#discussion_r1782523357

### CODE REVIEW

**Review by PizieDust — APPROVED** [review]
Looks good to me. Thanks @hannesm

File: src/vmm_core.ml [hunk 1]
```diff
@@ -241,21 +241,23 @@ module Policy = struct
...
       Error (`Msg "Unusable policy with no CPUids")
     else if memory <= 16 then
-      Error (`Msg "Unusable policy with memory <= 16 MB")
-    else
-      Ok ()
+      Error (`Msg ("Unusable policy with memory " ^ string_of_int memory ^ " MB <= 16 MB"))
+    else match block with
+      | None -> Ok ()
+      | Some x when x >= 0 -> Ok ()
+      | Some x -> Error (`Msg ("Unusable policy with block " ^ string_of_int x ^ " MB < 0 MB"))
```
Comment (reynir) [inline src/vmm_core.ml:260]: I'm not sure it's exactly unusable as it would be equivalent to `None`. It's a redundant representation, though. I guess this could break policies made previously?!

Comment (reynir) [reply src/vmm_core.ml:260]: Ah, `Vmm_core.Policy.usable` is only ever called in the client before adding a new policy. So this should not break existing policies.

Comment (reynir) [reply src/vmm_core.ml:260]: Also, I'm not sure this is actually an unusable policy...

Comment (hannesm) [reply src/vmm_core.ml:260]: It's a check that if block is specified, it is > 0. I do think this makes sense, or doesn't it?

Comment (reynir) [reply src/vmm_core.ml:260]: Ah sorry you are right. I somehow read it as x > 0, and and x = 0 makes sense (if redundant)

**Review by reynir — APPROVED** [review]
